name: pazaakworld-nakama
logger:
  level: DEBUG
database:
  address:
    - nakama:local_nakama_password@postgres:5432/nakama?sslmode=disable
runtime:
  path: /nakama/data/modules
  js_entrypoint: pazaak-world.js
session:
  token_expiry_sec: 7200
socket:
  server_key: defaultkey
console:
  port: 7351
metrics:
  prometheus_port: 9100
